### ISSUE TITLE
Documents: Short links

### ISSUE THREAD

**Issue by timreyn** [cubingusa/org#25]
Create a handler cubingusa.org/doc/<document_short_name>, so that when uploading documents we can specify a link, so that we can keep these links from going stale as we upload new versions of documents.

**Comment by ToastyKen** [comment]
I want to emphasize that we SHOULD be allowed to set a doc's URL to one that already exists.. and have it clobber the old one (with a warning).  Here's what I imagine:

Upload Expense policy v1.0.
Set short link to expense-policy -> https://cubingusa.org/doc/expense-policy

Later, upload Expense policy v1.1.
Set short link to expense-policy

Warning: expose-policy currently points to Expense policy v1.0. Are you sure you want to make it point to this document instead?

If yes, it removes short link from old doc and points it to new doc.

This is my key usecase btw.

Also, the shortlinks should appear next to the docs in the documents page, for easy access.

**Comment by ToastyKen** [comment]
Actually, instead of short links being tied to the document upload page, I think it should just be its own independent page, so we can add custom short links to other things to, like google forms links and such.  (Downside would be that it might be easy to forget to upload short links on uploaded docs... so maybe ideally it'd be in both places.)
